apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::569182268976:user/Admin_Drew
      username: Admin_Drew
      groups:
        - system:masters
